### ISSUE TITLE
Switch to using pathlib everywhere

### ISSUE THREAD

**Issue by pudo** [alephdata/ingestors#26]
We are dealing with a lot of file paths, some of which may come as semi-broken Unicode thanks to the unix file system conventions. We should be passing around pathlib objects rather than strings of any sort in order to make path traversal happen.

**Comment by mgax** [comment]
We had this problem with Hoover. If you only pass around in-memory Python strings, you're fine, any broken unicode bytes will be surrogate-escaped (btw, pathlib uses strings internally anyway). Things get tricky if you want to store paths in a DB, because database drivers don't like Python's surrogate-escape mechanism, so you have to e.g. save them as bytes instead of text.

https://github.com/hoover/snoop2/blob/master/snoop/data/models.py#L246-L251

**Comment by pudo** [comment]
Thanks for the pointer! I hope that we can move away from storing paths in our database more and more, in part to account for stuff like this. The idea would be to store only hashes and file names which are purely descriptive, thus can be normalised in those surrogate edge cases.

**Comment by uhhhuh** [comment]
Here's the error message that we get from ingesting some files just for reference:
INFO:alephclient.tasks.crawldir:Upload [1144]: ___-______(24.08.2015)/12.2. \udcf1\udcd1\udcf5\udcbd\udcb4ԫ\udcd3\udcd9 .xlsx
ERROR:alephclient.tasks.crawldir:Failed [1144]: (partial)/Archives/___-______(24.08.2015)/12.2. \udcf1\udcd1\udcf5\udcbd\$
dcb4ԫ\udcd3\udcd9 .xlsx
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/alephclient/tasks/crawldir.py", line 56, in _upload
    _crawl_path(q, api, collection_id, languages, root_path, path)
  File "/usr/local/lib/python3.7/site-packages/alephclient/tasks/crawldir.py", line 45, in _crawl_path
    _upload_path(api, collection_id, languages, root_path, path)
  File "/usr/local/lib/python3.7/site-packages/alephclient/tasks/crawldir.py", line 41, in _upload_path
    api.ingest_upload(collection_id, file_path, metadata=metadata)
  File "/usr/local/lib/python3.7/site-packages/alephclient/api.py", line 238, in ingest_upload
    'file': (file_path.name, fh, MIME)
  File "/usr/local/lib/python3.7/site-packages/requests_toolbelt/multipart/encoder.py", line 125, in __init__
    self._prepare_parts()
  File "/usr/local/lib/python3.7/site-packages/requests_toolbelt/multipart/encoder.py", line 246, in _prepare_parts
    self.parts = [Part.from_field(f, enc) for f in self._iter_fields()]
  File "/usr/local/lib/python3.7/site-packages/requests_toolbelt/multipart/encoder.py", line 246, in <listcomp>
    self.parts = [Part.from_field(f, enc) for f in self._iter_fields()]
  File "/usr/local/lib/python3.7/site-packages/requests_toolbelt/multipart/encoder.py", line 236, in _iter_fields
    field.make_multipart(content_type=file_type)
  File "/usr/local/lib/python3.7/site-packages/urllib3/fields.py", line 174, in make_multipart
    (('name', self._name), ('filename', self._filename))
  File "/usr/local/lib/python3.7/site-packages/urllib3/fields.py", line 134, in _render_parts
    parts.append(self._render_part(name, value))
  File "/usr/local/lib/python3.7/site-packages/urllib3/fields.py", line 114, in _render_part
    return format_header_param(name, value)
  File "/usr/local/lib/python3.7/site-packages/urllib3/fields.py", line 45, in format_header_param
    value = email.utils.encode_rfc2231(value, 'utf-8')
  File "/usr/local/lib/python3.7/email/utils.py", line 246, in encode_rfc2231
    s = urllib.parse.quote(s, safe='', encoding=charset or 'ascii')
  File "/usr/local/lib/python3.7/urllib/parse.py", line 785, in quote
    string = string.encode(encoding, errors)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 6-10: surrogates not allowed

**Comment by pudo** [comment]
Fixed in #34.
